### ISSUE TITLE
The ROADMAP

### ISSUE THREAD

**Issue by JiffyRob** [JiffyRob/Treds-Adventure-v2#8]
Figured it would be good to add a list of features to add, in no particular order:
 - [ ] Enemies
 - [ ] Melee Combat
 - [ ] Range Combat
 - [x] Bombs & other explosions
 - [x] Item Menu & Item Usage
 - [ ] Magical Items (how to do these...?  I'm thinking do it scripting style.)
 - [ ] Dungeons & Lucite
 - [x] Layers
 - [ ] Pitfalls and fall walls
 - [x] OpenGL shading and optimization?
 - [x] `pygame.DirtySprite` optimization
 - [x] "Room Style" camera (thru OpenGL eventually)
 - [ ] Boss fights
 - [ ] Events and Story

**Comment by JiffyRob** [comment]
Note that OpenGL and pygame DirtySprite are marked complete when in reality they are not and never will be.
